name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_USER_NAME: ci
  CI_USER_EMAIL: ci@plezi.co
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  check_test:
    name: Check, test & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  prerelease:
    needs: [check_test]
    name: Pre-release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Display variables & commit message
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --tags
      - name: Git Setup
        run: |
          git config --global user.email $CI_USER_EMAIL
          git config --global user.name $CI_USER_NAME
          git config --global pull.ff only
          git checkout -b ci_processing
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Develop release
        run: npx -p conventional-changelog-conventionalcommits -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/exec -p semantic-release semantic-release

  release:
    needs: [check_test]
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Display variables & commit message
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --tags
      - name: Git Setup
        run: |
          git config --global user.email $CI_USER_EMAIL
          git config --global user.name $CI_USER_NAME
          git config --global pull.ff only
          git checkout -b ci_processing
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Release
        run: npx -p conventional-changelog-conventionalcommits -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/exec -p semantic-release semantic-release
      - name: Update back develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff master develop -X theirs -m "chore(merge): auto merge master to develop"
          git push origin develop
